FROM alpine:latest

WORKDIR /app

COPY /meta/local-dev/nginx.conf /etc/nginx/nginx.conf

RUN sed -e '/community/{p;s@v[^/]*/@edge/@;s@community@testing@}' -i /etc/apk/repositories && \
	apk update && \
	apk upgrade && \
	apk add curl openresty tini zsh && \
	mkdir -p /var/tmp/nginx

VOLUME ["/app/public"]

EXPOSE 80

ENTRYPOINT ["/sbin/tini"]
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
