# Generated by Django 3.2.14 on 2023-04-12 15:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=512, unique=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Country code"
                    ),
                ),
                (
                    "iso_a2_code",
                    models.CharField(max_length=2, null=True, verbose_name="Alpha 2"),
                ),
                (
                    "iso_a3_code",
                    models.CharField(max_length=3, null=True, verbose_name="Alpha 3"),
                ),
                (
                    "locale_code",
                    models.CharField(
                        default=None,
                        max_length=8,
                        null=True,
                        verbose_name="Locale code",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Ignore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=512, unique=True, verbose_name="Name"),
                ),
                (
                    "domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignore",
                "verbose_name_plural": "Ignore",
            },
        ),
        migrations.CreateModel(
            name="ProxyConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Config name"
                    ),
                ),
                (
                    "server",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Proxy server"
                    ),
                ),
                ("port", models.CharField(max_length=6, verbose_name="Proxy port")),
                (
                    "ping_host",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Proxy ping host",
                    ),
                ),
                (
                    "ping_port",
                    models.CharField(
                        default=0, max_length=6, verbose_name="Proxy ping port"
                    ),
                ),
                ("weight", models.IntegerField(default=0, verbose_name="Weight")),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Proxy config",
                "verbose_name_plural": "Proxy Configs",
                "ordering": ["-weight"],
            },
        ),
        migrations.CreateModel(
            name="CountryRegistry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2048),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country Registry",
                "verbose_name_plural": "Country Registries",
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registry_url",
                    models.URLField(blank=True, null=True, verbose_name="Registry URL"),
                ),
                (
                    "custom_registry_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Custom Registry URL"
                    ),
                ),
                (
                    "specifics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Specifics"
                    ),
                ),
                ("proxy_url", models.URLField(null=True, verbose_name="Proxy URL")),
                (
                    "ignore_url",
                    models.URLField(blank=True, null=True, verbose_name="Ignore URL"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Config",
                "verbose_name_plural": "Configs",
            },
        ),
    ]
