# Generated by Django 3.0.5 on 2021-06-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_props"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="locale_code",
            field=models.CharField(
                default=None, max_length=8, null=True, verbose_name="Locale code"
            ),
        ),
    ]
