# Generated by Django 3.0.5 on 2021-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_locale_code_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="custom_registry_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Custom Registry URL"
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="registry_url",
            field=models.URLField(blank=True, null=True, verbose_name="Registry URL"),
        ),
        migrations.AlterField(
            model_name="config",
            name="report_endpoint",
            field=models.URLField(
                blank=True, null=True, verbose_name="DPI API Endpoint"
            ),
        ),
    ]
