# Generated by Django 3.0.5 on 2021-07-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_allow_blank_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Config name")),
                (
                    "server",
                    models.CharField(max_length=256, verbose_name="Proxy server"),
                ),
                ("port", models.CharField(max_length=6, verbose_name="Proxy server")),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (0, "Default"),
                        ],
                        default=0,
                        verbose_name="Priority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxy config",
                "verbose_name_plural": "Proxy Configs",
                "ordering": ["-priority"],
            },
        ),
    ]
