# Generated by Django 3.0.5 on 2021-07-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_proxy_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxyconfig",
            name="ping_port",
            field=models.CharField(
                default=0, max_length=6, verbose_name="Proxy ping port"
            ),
        ),
    ]
