# Generated by Django 3.0.5 on 2022-02-22 13:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_ping_port"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryRegistry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2048),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country Registry",
                "verbose_name_plural": "Country Registries",
            },
        ),
    ]
