# Generated by Django 3.1.14 on 2022-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_countryregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyconfig',
            name='ping_host',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Proxy ping host'),
        ),
    ]
