# Generated by Django 3.1.14 on 2022-03-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_ping_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxyconfig",
            name="port",
            field=models.CharField(max_length=6, verbose_name="Proxy port"),
        ),
    ]
