# Generated by Django 3.1.14 on 2022-03-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_make_fields_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyconfig',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
