# Generated by Django 3.1.14 on 2022-03-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_active_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proxyconfig",
            options={
                "ordering": ["-weight"],
                "verbose_name": "Proxy config",
                "verbose_name_plural": "Proxy Configs",
            },
        ),
        migrations.RemoveField(
            model_name="proxyconfig",
            name="priority",
        ),
        migrations.AddField(
            model_name="proxyconfig",
            name="weight",
            field=models.IntegerField(default=0, verbose_name="Weight"),
        ),
    ]
