# Generated by Django 3.1.14 on 2022-03-28 20:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ignore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=512, unique=True, verbose_name="Name"),
                ),
                (
                    "domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignore",
                "verbose_name_plural": "Ignore",
            },
        ),
    ]
