# Generated by Django 3.1.14 on 2022-04-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_ignore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="report_endpoint",
        ),
    ]
