# Generated by Django 3.1.14 on 2022-04-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_deprecated_models_and_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="specifics",
            field=models.JSONField(blank=True, default=dict, verbose_name="Specifics"),
        ),
    ]
