# Generated by Django 3.2.13 on 2022-10-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_fix_field_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="proxy_url",
            field=models.URLField(null=True, verbose_name="Proxy URL"),
        ),
    ]
