# Generated by Django 3.2.13 on 2022-10-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_proxy_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ignore_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ignore URL'),
        ),
    ]
