# Generated by Django 3.0.5 on 2020-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_allow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=128, verbose_name='Domain'),
        ),
    ]
