# Generated by Django 3.0.5 on 2020-07-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_make_field_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='client_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Client Hash'),
        ),
        migrations.AddField(
            model_name='domain',
            name='client_provider',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Client provider'),
        ),
        migrations.AddField(
            model_name='domain',
            name='client_region',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Client region'),
        ),
    ]
