# Generated by Django 3.0.5 on 2021-08-11 14:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_reported_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="ct_meta_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="CensorTracker's meta info"
            ),
        ),
    ]
