# Generated by Django 3.1.14 on 2022-04-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_add_user_agent_field"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Case",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
    ]
